services:
 vito.db.sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1401:1433"
    volumes: 
      - vito.db.sqlserver.data:/var/opt/mssql
    environment:
      MSSQL_SA_PASSWORD: "Vito2025+"
      ACCEPT_EULA: Y
    networks:
      network-name:
        aliases:
          - vito.sql.server
 Vito.Transverse.Identity.Presentation.Api:
    image: ${DOCKER_REGISTRY-}vitotransverseidentityapi
    build:
      context: .
      dockerfile: Vito.Transverse.Identity.Presentation.Api/Dockerfile
    networks:
      network-name:
        aliases:
          - vito.transverse.api.server
volumes:
  vito.db.sqlserver.data:
networks:
  network-name: {}
